### PR TITLE
Ignore state

### PR DESCRIPTION
**Pull request by nephantes**

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Anything I can help with here?

**Comment by nephantes** [comment]
We had a problem about state change in the browser when we deploy it to shiny-server. We just don't return error in that case and solved temporarily.

**Comment by MarkEdmondson1234** [comment]
Ok, its a good idea to keep it as it stops people hijacking your authentication, but you can also set it via `options(googleAuthR.securitycode)` if that helps at all.

**Comment by nephantes** [comment]
Thanks Mark!

**Pull request closed without merging**
