### PR TITLE
Fix incomplete auto api generation [#125]

### PR DESCRIPTION
**Pull request by alberthkcheng**
- force recursive to get whole list of methods
- remove duplicated method
- fixed auto-generated function naming

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Thank you!  Will review when finished moving house :)

**Comment by MarkEdmondson1234** [comment]
tried To merge today but the check for coverage is failed, need a test to cover the new code if possible.

**Comment by alberthkcheng** [comment]
Do you have any idea on what can be tested?

All those thing depends on google api dynamically, I cannot hardcode the test case.

**Comment by MarkEdmondson1234** [comment]
It can be done with mocking the api response or calling the api in the test, but I’ll have a look you don’t need to implement it unless you feel the need :)

**Comment by MarkEdmondson1234** [comment]
I'll merge this anyway and look at the tests later.  Thanks for the contribution!

**Pull request merged**
